-- data.sql

INSERT INTO COUNTRIES (id, name) VALUES (1, 'USA');
INSERT INTO COUNTRIES (id, name) VALUES (2, 'FRANCE');
INSERT INTO COUNTRIES (id, name) VALUES (3, 'ITALY');
INSERT INTO COUNTRIES (id, name) VALUES (4, 'JAPAN');
INSERT INTO COUNTRIES (id, name) VALUES (5, 'SPAIN');
