-- import.sql

-- CAFE
INSERT INTO CAFE (ID, RATING, TITLE, CITY, COUNTRY, SITE, FACEBOOK, EMAIL, PHONE, STYLE, ADDRESS, DESCRIPTION, OPEN_AT, CLOSE_AT) VALUES (1, 1, 'Masanielli Francesco Martucci', 'Caserta', 'Italy', 'http://www.pizzeriaimasanielli.it', 'https://www.facebook.com/masaniellifrancescomartucci', 'info@pizzeriaimasanielli.it', '+0823 154 0786','napoletano', 'address ', 'Francesco Martucci continues his personal evolution in his gastronomic initiative applied to pizza, an internationally popular dish...', '9:00:00', '23:00:00');
INSERT INTO CAFE (ID, RATING, TITLE, CITY, COUNTRY, SITE, FACEBOOK, EMAIL, PHONE, STYLE, ADDRESS, DESCRIPTION, OPEN_AT, CLOSE_AT) VALUES (2, 3, 'Peppe Pizzeria', 'Paris', 'France', 'http://www.peppeparis.fr/it/', 'https://www.facebook.com/masaniellifrancescomartucci', 'info@peppeparis.fr', '+33 1 45 35 59 13','napoletano', '2 Place Saint Blaise, Reservation, 75020 Paris', 'The energy of Peppe Cutraro transpires here, in the style as well as in the welcoming Italian hospitality, friendliness, and attentiveness...', '8:30:00', '22:30:00');
INSERT INTO CAFE (ID, RATING, TITLE, CITY, COUNTRY, SITE, FACEBOOK, EMAIL, PHONE, STYLE, ADDRESS, DESCRIPTION, OPEN_AT, CLOSE_AT) VALUES (3, 2, 'Tonys Pizza Napoletana', 'San Francisco', 'USA', 'http://www.tonyspizzanapoletana.com', 'https://www.facebook.com/tonyspizza415', 'info@tonyspizzanapoletana.com', '+1 415-835-9888','napoletano', '1570 Stockton St, San Francisco, CA 94133', 'This is a traditional venue for high-quality pizza located right in the heart of San Francisco...', '9:00:00', '22:45:00');
INSERT INTO CAFE (ID, RATING, TITLE, CITY, COUNTRY, SITE, FACEBOOK, EMAIL, PHONE, STYLE, ADDRESS, DESCRIPTION, OPEN_AT, CLOSE_AT) VALUES (4, 5, 'Sartoria Panatieri', 'Barselona', 'Spain', 'http://www.sartoriapanatieri.com', 'https://www.facebook.com/sartoriapanatieri', 'info@sartoriapanatieri.com', '+34 931 37 63 85','napoletano', 'Carrer de Provença, 330, 08037 Barcelona, Spagna', 'The pizzas use a dough made from local organic flours...', '8:00:00', '23:00:00');
INSERT INTO CAFE (ID, RATING, TITLE, CITY, COUNTRY, SITE, FACEBOOK, EMAIL, PHONE, STYLE, ADDRESS, DESCRIPTION, OPEN_AT, CLOSE_AT) VALUES (5, 4, 'Pizzeria Peppe – Napoli sta ca', 'Tokyo', 'Japan', 'http://www.peppenapolistaca.com', 'https://www.facebook.com/peppenapolistaca', 'info@peppenapolistaca.com', '+81 3-6459-1846','napoletano', 'Giappone, 〒106-0041 Tokyo, Minato City, Azabudai, 1', 'The pizzas use a dough made from local organic flours...', '7:00:00', '23:00:00');

-- PIZZA
INSERT INTO PIZZA(NAME, SIZE, DESCRIPTION, KEY_INGREDIENTS, PRICE) VALUES ('Margaritha', 'S', 'The most famous pizza...', '', 10.90);
INSERT INTO PIZZA(NAME, SIZE, DESCRIPTION, KEY_INGREDIENTS, PRICE, IS_SPICY) VALUES ('Bacon Double Cheese', 'M', 'Bacon, ground beef, tomatoes, extra mozzarella cheese. 243kcal, 1020kJ / large slice / classic crust. from 739 kcal • from 1 serving', 'Bacon', 12.5, true);
INSERT INTO PIZZA(NAME, SIZE, DESCRIPTION, KEY_INGREDIENTS, PRICE) VALUES ('Vegi Supreme', 'B', 'Onions, green and red peppers, sweetcorn, mushrooms, tomatoes. 202kcal, 848kJ / large slice / classic crust. from 615 kcal • from 1 serving', 'Mushrooms', 11.0);
INSERT INTO PIZZA(NAME, SIZE, DESCRIPTION, KEY_INGREDIENTS, PRICE) VALUES ('Peperoni', 'L', 'Extra pepperoni and extra mozzarella cheese on a Domino-s tomato sauce base. 264kcal, 1110kJ / large slice / classic crust. from 788 kcal • from 1 serving', 'Peperoni', 15.90);
INSERT INTO PIZZA(NAME, SIZE, DESCRIPTION, KEY_INGREDIENTS, PRICE, IS_SPICY) VALUES ('American Hot', 'S', 'Onions, pepperoni, green jalapeño peppers. 233kcal, 979kJ / large slice / classic crust. from 700 kcal • from 1 serving', 'Onion', 15.0, true);
INSERT INTO PIZZA(NAME, SIZE, DESCRIPTION, KEY_INGREDIENTS, PRICE) VALUES ('Four cheese', 'XL', 'Four sorts of cheese...', 'Cheese', 14.90);
INSERT INTO PIZZA(NAME, SIZE, DESCRIPTION, KEY_INGREDIENTS, PRICE) VALUES ('Meat', 'S', 'Meat pizza... eat pizza...', 'Meat',  22.90);
INSERT INTO PIZZA(NAME, SIZE, DESCRIPTION, KEY_INGREDIENTS, PRICE) VALUES ('Texas BBQ', 'S', 'Tangy bbq sauce topped with smoky bacon, chicken breast strips, onions, green and red peppers. 231kcal, 970kJ / large slice / classic crust. from 727 kcal • from 1 serving', 'Chicken', 15.90);
INSERT INTO PIZZA(NAME, SIZE, DESCRIPTION, KEY_INGREDIENTS, PRICE) VALUES ('Burger Pizza', 'S', 'Pizza and burger at the same time - it is possible...', '', 16.99);

